import type { InventoryItem } from '@/types/inventory';

export const placeholderInventory: InventoryItem[] = [
  {
    id: '1',
    name: 'Volkswagen Amarok 2018',
    kms: 120000,
    purchasePrice: 2000000,
    salePrice: 3500000,
    type: 'Propia',
    status: { name: 'ok' },
    imageUrl: 'https://images.jazelc.com/uploads/galpinvolkswagen-m2en/2022-Volkswagen-Taos-31.png',
    imageHint: 'black pickup',
  },
  {
    id: '2',
    name: 'Toyota Hilux 2020',
    kms: 85000,
    purchasePrice: 3500000,
    salePrice: 5100000,
    type: 'Propia',
    status: { name: 'ok' },
    imageUrl: 'https://images.jazelc.com/uploads/galpinvolkswagen-m2en/2022-Volkswagen-Taos-31.png',
    imageHint: 'white pickup',
  },
  {
    id: '3',
    name: 'Ford Ecosport 2017',
    kms: 70000,
    purchasePrice: 1600000,
    salePrice: 3000000,
    type: 'Flip compartido',
    status: { name: 'En riesgo', days: 45 },
    imageUrl: 'https://images.jazelc.com/uploads/galpinvolkswagen-m2en/2022-Volkswagen-Taos-31.png',
    imageHint: 'silver suv',
  },
  {
    id: '4',
    name: 'Ford E:150 2015',
    kms: 50000,
    purchasePrice: 5200000,
    salePrice: 6700000,
    type: 'Flip compartido',
    status: { name: 'ok' },
    imageUrl: 'https://images.jazelc.com/uploads/galpinvolkswagen-m2en/2022-Volkswagen-Taos-31.png',
    imageHint: 'silver van',
  },
  {
    id: '5',
    name: 'Nissan Frontier 2020',
    kms: 80000,
    purchasePrice: 3400000,
    salePrice: 4800000,
    type: 'Flip compartido',
    status: { name: 'ok' },
    imageUrl: 'https://images.jazelc.com/uploads/galpinvolkswagen-m2en/2022-Volkswagen-Taos-31.png',
    imageHint: 'black pickup',
  },
   {
    id: '6',
    name: 'Toyota 2019',
    kms: 60000,
    purchasePrice: 8000000,
    salePrice: 9450000,
    type: 'Flip compartido',
    status: { name: 'ok' },
    imageUrl: 'https://images.jazelc.com/uploads/galpinvolkswagen-m2en/2022-Volkswagen-Taos-31.png',
    imageHint: 'gray car',
  },
  {
    id: '7',
    name: 'Peugeot 208',
    kms: 20000,
    purchasePrice: 3000000,
    salePrice: 4500000,
    type: 'Flip compartido',
    status: { name: 'ok' },
    imageUrl: 'https://images.jazelc.com/uploads/galpinvolkswagen-m2en/2022-Volkswagen-Taos-31.png',
    imageHint: 'dark car',
  },
  {
    id: '8',
    name: 'Renault Duster 2021',
    kms: 45000,
    purchasePrice: 2800000,
    salePrice: 4200000,
    type: 'Propia',
    status: { name: 'ok' },
    imageUrl: 'https://images.jazelc.com/uploads/galpinvolkswagen-m2en/2022-Volkswagen-Taos-31.png',
    imageHint: 'blue suv',
  },
];
